baseURL: ""
languageCode: "en-us"
title: "Randeep Singh"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

params:
  title: "Randeep Singh"
  description: A collection of information about Randeep Singh and any projects he has worked on.

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: true

  animate: true

  theme:
    disableThemeToggle: false
    defaultTheme: "dark"

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  color:
    darkmode:
      textColor: "#F5F5F5"
      secondaryTextColor: "#F5F5F5"
      backgroundColor: "#313552"
      primaryColor: "#F1E0AC"
      secondaryColor: "#30475E"

  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandName: "Randeep Singh"
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Randeep."
    subtitle: "I build applications."
    content: "A passionate computer scientist with primary focus on programming. I tend to use modern technologies to create websites that are functional & appealing."
    image: /Images/Bitmoji.png
    button:
      enable: true
      name: "Resume"
      url: "/resume/Resume.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/RaSingh02/
        - icon: fab fa-linkedin-in
          url: https://www.linkedin.com/in/randeep-singh-8096b31a5/

  # About
  about:
    enable: true
    title: "About Me"
    content: |-
      I am a software developer with a passion for web and application development. I am currently working towards my Computer Science BS degree with a minor in mathematics at Clarkson University.

      I am currently not working on any projects due to school. However, I am currently looking for internships and full-time positions starting June 2023.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Amazon Web Services"
        - "JavaScript"
        - "TypeScript"
        - "Python"
        - "Java"
        - "C++"
        - "MongoDB"
        - "SQL"
        - "HTML"
        - "CSS"
        - "React"
        - "Node"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Engineer Intern"
        company: "Green Action Studio"
        companyUrl: "https://greenactionstudio.com/"
        date: "May 2022 - August 2022"
        featuredLink:
          enable: true
          name: "One of the projects I worked on"
          url: "https://apps.apple.com/us/app/charge-port-ev-charging/id1581494936"
        content: |-
          Migrated the old backend to a new event-driven architecture using Amazon Web Services.
          Developed and integrated multiple new backend APIs using Node.js, Amazon Web Services, MongoDB, TypeScript.
          Developed and integrated a new feature to the mobile application using React Native.
          Increased code coverage by implementing unit tests using Jest.

  # Education
  education:
    enable: true
    index: true
    items:
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Clarkson University"
          url: "https://www.clarkson.edu/"
        date: "2020 - 2023"
        GPA: "3.1 out of 4.0"
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Mohonasen High School"
          url: "https://www.mohonasen.org/"
        date: "2016 - 2020"
        GPA: "3.3 out of 4.0"
        content: |-
          Extracurricular Activities
            - National Honor Society Member: 2018 - 2020
            - Secretary of Robotics Club
            - Siena College High School Programming Contest: 2018

  # projects
  projects:
    enable: true
    items:
      - title: Charge Port EV Charging
        content: Green Action Studio's mobile application. I worked on adding a new stage to let users know to plug-in the cable to their vehicle. Worked on the backend API from the ground up using AWS Cloud Services.
        image: /Images/projects/chargeport.png
        badges:
          - "TypeScript"
          - "React Native"
          - "AWS Cloud Services"
          - "TailwindCSS"
          - "MongoDB"
          - "Node"
        links:
          - icon: fab fa-link
            url: https://apps.apple.com/us/app/charge-port-ev-charging/id1581494936

      - title: Back-End API
        content: External API for Green Action Studio that connects multiple different microservices and applications together uisng AWS Cloud Services. Worked on the API from the ground up and connected it to the new Charge Port API.
        image: /Images/projects/aws.jpg
        badges:
          - "TypeScript"
          - "AWS Cloud Services"
          - "MongoDB"
          - "Node"

      - title: Weather App
        content: A basic react based weather app using OpenWeather's API. More information can be found on the GitHub repo.
        image: /Images/projects/weather.png
        featured:
          name: Demo
          link: https://www.randeepsingh.dev/weather/
        badges:
          - "React"
          - "HTML"
          - "CSS"
        links:
          - icon: fab fa-github
            url: https://github.com/RaSingh02/weather-website

      - title: Fetch API App
        content: Basic fetch API app for South Park characters. More information can be found on the GitHub repo.
        image: /Images/projects/fetch.JPG
        featured:
          name: Demo
          link: https://rasingh02.github.io/fetch-api-app/
        badges:
          - "HTML"
          - "JavaScript"
          - "CSS"
        links:
          - icon: fab fa-github
            url: https://github.com/RaSingh02/fetch-api-app

      - title: Random Quotes App
        content: This mini-web page is a random quote generator, that allows the user to generate another random quote or go back to the previous quote. Each time the generate button is pressed, a randomly generated image is displayed as the background. There are some animations on the buttons and the title using the anime.css library. There are a total of 12 quotes and 12 background images. However, the images are randomly generated each time the page is refreshed. The images are sourced using Lorem Picsum.
        image: /Images/projects/quote.png
        featured:
          name: Demo
          link: https://rasingh02.github.io/quotes-app/
        badges:
          - "JavaScript"
          - "CSS"
          - "HTML"
        links:
          - icon: fab fa-github
            url: https://github.com/RaSingh02/quotes-app

      - title: Bootstrap Storefront
        content: A basic storefront example made primarily using the BootStrap framework.
        image: /Images/projects/bookstore.png
        featured:
          name: Demo
          link: https://rasingh02.github.io/storefront/
        badges:
          - "CSS"
          - "HTML"
        links:
          - icon: fab fa-github
            url: https://github.com/RaSingh02/storefront

      - title: Game Library
        content: A simple game library consiting of a couple of games within the website. Can play against computer for tic-tac-toe or person.
        image: /Images/projects/games.png
        featured:
          name: Demo
          link: https://rasingh02.github.io/game-library/
        badges:
          - "CSS"
          - "HTML"
          - "JavaScript"
        links:
          - icon: fab fa-github
            url: https://github.com/RaSingh02/game-library

      - title: CS350 Team Website
        content: A team website for CS350 that was made using the Bootstrap framework. Has team documents and weekly reports along with about us cards.
        image: /Images/projects/team.png
        featured:
          name: Demo
          link: https://rasingh02.github.io/team-website/
        badges:
          - "HTML"
          - "CSS"
        links:
          - icon: fab fa-github
            url: https://github.com/RaSingh02/team-website

      - title: RecipeBuddy
        content: Semester project for CS350. A application to store recipes with functionality to see recipies, add, remove, and edit them.
        image: /Images/projects/recipebuddy.png
        # featured:
        #   name: Demo
        #   link: https://recipebuddy-ppsm.herokuapp.com/
        badges:
          - "JavaScript"
          - "CSS"
          - "HTML"
          - "Python"
        links:
          - icon: fab fa-github
            url: https://github.com/RaSingh02/RecipeBuddy

  #Contact
  contact:
    enable: true
    content: Feel free to contact me for any questions or if you just want to connect!
    email: ra.singh0502@gmail.com
    btnName: Send

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: true
    socialNetworks:
      github: https://github.com/RaSingh02/
      linkedin: https://www.linkedin.com/in/randeep-singh-8096b31a5/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
